-- Only Me & You — LoveStory v2
-- Prototype shared room database.
-- IMPORTANT: for production, replace room-code-only access with authenticated
-- membership/RLS tied to auth.uid(). This schema is intended to get the realtime
-- prototype running quickly.

create table if not exists public.couple_rooms (
  id bigint generated by default as identity primary key,
  room_code text unique not null,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.couple_rooms enable row level security;

drop policy if exists "oamy_select" on public.couple_rooms;
drop policy if exists "oamy_insert" on public.couple_rooms;
drop policy if exists "oamy_update" on public.couple_rooms;

create policy "oamy_select" on public.couple_rooms
for select to anon, authenticated using (true);

create policy "oamy_insert" on public.couple_rooms
for insert to anon, authenticated with check (true);

create policy "oamy_update" on public.couple_rooms
for update to anon, authenticated using (true) with check (true);

alter table public.couple_rooms replica identity full;
